name: final exam
on: [push]
jobs:
    job1:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodes: [16,18]
        steps:
            
            - name: checkout repository
              uses: actions/checkout@v4
            
            - name: Node version 16 and 18
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.nodes}}
                
            - name: Install newman
              run: npm install -g newman
            
            - name: run newman
              run: newman run postman_tests/Books.postman_collection.json -e postman_tests/test.postman_environment.json
